# action.yml
name: 'MCF to ISO'
description: 'action converts contents of a folder in repository to ISO metadata'
inputs:
  folder-input:  # id of input
    description: 'Folder to process'
    required: true
    default: '.'
  folder-output:  # id of input
    description: 'Folder to export to'
    required: true
    default: 'export'
outputs:
  status: # id of output
    description: 'Status'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.folder-input }}
    - ${{ inputs.folder-output }}