# action.yml
name: 'ttl to html'
description: 'The action converts contents of a ttl file into html using widoco'
inputs:
  file-input:  # id of input
    description: 'File to process'
    required: true
  folder-output:  # id of input
    description: 'Folder for output'
    required: true
  options:  # id of input
    description: 'Processing options'
    required: false
    default: ''
outputs:
  status: # id of output
    description: 'Status'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file-input }}
    - ${{ inputs.folder-output}}
    - ${{ inputs.options }}